using Romeilter.Models;

namespace Romeilter.StaticServices;
public static class RecipeService
{
    public static HashSet<AlchemyRecipeModel> AlchemyRecipes = [
        new () {
            Name = "Stärketrank",
            Description = "Stärkt den Körper für kurze Zeit",
            Effect = "(Fertigkeit) Boni auf Handeln für 1 Minute",
            FirstIngredient = PlantService.Mate,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = true,
            Rarity = Rarity.Uncommon,
            Cost = 5,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Schwächungswurftrank",
            Description = "Stärkt den Körper für kurze Zeit",
            Effect = "(Fertigkeit + Wasseranteil) Boni auf Handeln für 1 Minute, verdunstungsbereich (Fertigkeit + Alkoholanteil)",
            FirstIngredient = PlantService.Blutwurz,
            SecondIngredient = PlantService.Water,
            ThirdIngredient = PlantService.Alcohol,
            Grenade = true,
            Positive = false,
            Rarity = Rarity.Uncommon,
            Cost = 7,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Heiltrank",
            Description = "Heilt mittlere Wunden",
            Effect = "(Fertigkeit) + W10 Lebenspunkte",
            FirstIngredient = PlantService.Athelas,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = true,
            Rarity = Rarity.Common,
            Cost = 1,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Hayatiextrakt",
            Description = "Extrakt der Hayati, regeneriert den Körper und verkürzt benötigte die Zeit zum Rasten. Kann bei übermäßigem oder konsekutiven gebrauch zu Nebeneffekten führen",
            Effect = "(Fertigkeit) Stunden weniger benötigte Rast.",
            FirstIngredient = PlantService.Hayati,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = true,
            Rarity = Rarity.Uncommon,
            Cost = 5,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Rauchgranate",
            Description = "Produziert ein einem Bereich einen dichten Rauch, der das Sehen stark beeinträchtigt",
            Effect = "(Fertigkeit) Malus auf Handeln von Sichttätigkeiten. Verdunstungsbereich (Fertigkeit)",
            FirstIngredient = PlantService.Rauchkraut,
            SecondIngredient = PlantService.Alcohol,
            Grenade = true,
            Positive = true,
            Rarity = Rarity.Uncommon,
            Cost = 5,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Schwebetrank",
            Description = "Lässt den Anwender sehr leicht werden, wodurch dieser um einiges weiter / höher springen kann und keine Brüche bei der Landung erwarten muss.",
            Effect = "(Fertigkeit) Bonus auf Sprungreichweite für 1 Minute. Verhindert fallschaden",
            FirstIngredient = PlantService.Blutkraut,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = true,
            Rarity = Rarity.Rare,
            Cost = 15,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Schlaftrunk",
            Description = "Lässt den Anwender in einen tiefen Schlaf fallen, von dem er nur schwer aufgeweckt werden kann.",
            Effect = "Tiefer Schlaf für (Fertigkeit) Stunden",
            FirstIngredient = PlantService.Schlafbeeren,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = false,
            Rarity = Rarity.Uncommon,
            Cost = 6,
            Currency = Currency.Silver,
        },
        new () {
            Name = "Eisenhutgift",
            Description = "Ein simples aber in hoher konzentration tötliches Gift. Schmeckt und riecht leicht nach Eisen.",
            Effect = "(Fertigkeit) W10 an Schaden",
            FirstIngredient = PlantService.Eisenhut,
            SecondIngredient = PlantService.Water,
            Grenade = false,
            Positive = false,
            Rarity = Rarity.Common,
            Cost = 3,
            Currency = Currency.Silver,
        },
    ];
}